In [42]:
import numpy as np

In [43]:
arr = np.array([[3,6,36,78]], np.int8)

TypeError: 'numpy.ndarray' object is not callable

In [44]:
arr

array([[ 3, 45, 36, 78]], dtype=int8)

In [ ]:
arr[0,1]

6

In [ ]:
arr.shape

(1, 4)

In [ ]:
arr.dtype

dtype('int8')

In [ ]:
arr[0,1] = 45

In [ ]:
arr

array([[ 3, 45, 36, 78]], dtype=int8)

In [ ]:
ar2 = np.array = np.array([[1,2,3],[4,5,6],[7,8,9]])
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ar2.size

9

In [ ]:
zeros = np.zeros((2,5))

In [ ]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
lspace = np.linspace(1,5,12)

In [ ]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [ ]:
emp = np.empty((4,6))

In [ ]:
emp

array([[4.67296746e-307, 1.69121096e-306, 8.90095411e-307,
        1.89146896e-307, 7.56571288e-307, 3.11525958e-307],
       [1.24610723e-306, 8.45593934e-307, 9.34600963e-307,
        2.22518251e-306, 1.33511969e-306, 1.78019761e-306],
       [9.34608432e-307, 1.33512376e-306, 1.11261570e-306,
        3.56027436e-307, 1.37961641e-306, 8.34424342e-308],
       [1.51317924e-306, 1.33508031e-306, 1.60219170e-306,
        8.90124610e-308, 0.00000000e+000, 1.94693963e-308]])

In [ ]:
emp_like = np.empty_like(lspace)

In [ ]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [ ]:
ide = np.identity(23)

In [ ]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0.,

In [ ]:
ide.shape

(23, 23)

In [ ]:
arr2 = np.arange(99)

In [ ]:
arr2 = arr2.reshape(3,33)

In [ ]:
arr2.shape

(3, 33)

In [ ]:
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
aar = np.array([[1,2,3],[4,5,6],[7,8,9]])

TypeError: 'numpy.ndarray' object is not callable