In [8]:
import numpy as np

In [9]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
ar = np.array(x)

In [13]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
ar.sum(axis=0)

array([12, 15, 18])

In [15]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [16]:
ar.prod(axis=0)

array([ 28,  80, 162])

In [17]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [19]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [20]:
ar.ndim

2

In [21]:
ar.size

9

In [22]:
ar.nbytes

36

In [23]:
one = np.array([1,3,6,76,453])

In [24]:
one.argmax()

4

In [25]:
one.argmin()

0

In [26]:
one.argsort()

array([0, 1, 2, 3, 4], dtype=int64)

In [29]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [30]:
ar.ravel

<function ndarray.ravel>

In [31]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [32]:
ar3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
ar + ar3

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [36]:
ar2 = ar*ar3

In [37]:
np.sqrt(ar2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [38]:
ar.max()

9

In [39]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [40]:
np.count_nonzero(ar)

9

In [41]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [42]:
ar[1,2] = 0

In [43]:
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 9]])

In [44]:
import sys

In [45]:
checkar = [0,4,55,2]

In [46]:
npar = np.array(checkar)

In [47]:
sys.getsizeof(1)*len(npar)

112

In [49]:
npar.itemsize*npar.size

16